import java.awt.image.BufferedImage;
import java.awt.image.PixelGrabber;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;

public class Strings {
   public static String aa = "Trust this computer";
   public static String Strings_select = "Select";
   public static String Strings_hidden = "Hidden";
   public static String Strings_loadedTitleScreen = "Loaded title screen";
   public static String Strings_loadingConfig = "Loading config - ";
   public static String Strings_membersObject = "Members object";
   public static String Strings_startingGameEngine = "Starting game engine...";
   public static String Strings_preparedVisibilityMap = "Prepared visibility map";
   public static String Strings_pleaseWaitAttemptingToReestablish = "Please wait - attempting to reestablish";
   public static String Strings_loadingFonts = "Loading fonts - ";
   public static String Strings_loadedFonts = "Loaded fonts";
   public static String al = "Discard";
   public static String Strings_loadedUpdateList = "Loaded update list";
   public static String Strings_take = "Take";
   public static String Strings_loadingPleaseWait = "Loading - please wait.";
   public static String Strings_loadedConfig = "Loaded config";
   public static String Strings_continue = "Continue";
   public static String Strings_checkingForUpdates = "Checking for updates - ";
   public static String Strings_preparedSoundEngine = "Prepared sound engine";
   public static String Strings_null = "null";
   public static String Strings_ok = "Ok";
   public static String Strings_connectingToUpdateServer = "Connecting to update server";
   public static String Strings_drop = "Drop";
   public static String Strings_connectionLost = "Connection lost";
   public static String ay = "for 30 days: ";
   public static String Strings_loadingTitleScreen = "Loading title screen - ";
   public static String ba = " seconds.";
   public static String Strings_loadedSprites = "Loaded sprites";
   public static String bc = "Error connecting to server.";
   public static String Strings_loadingWorldMap = "Loading world map - ";
   public static String Strings_loadedTextures = "Loaded textures";
   public static String bf = "You have only just left another world.";
   public static String bg = "Please enter a 6-digit PIN.";
   public static String bh = "Please try using a different world.";
   public static String Strings_loadingTextures = "Loading textures - ";
   public static String Strings_loadedInputHandler = "Loaded input handler";
   public static String bl = "Please try using a different world.";
   public static String Strings_loadedInterfaces = "Loaded interfaces";
   public static String bn = "View Appeal Options";
   public static String Strings_loadedWordpack = "Loaded wordpack";
   public static String bp = "";
   public static String bq = "Your profile will be transferred in:";
   public static String br = "";
   public static String bs = "Recover Account";
   public static String Strings_loadedWorldMap = "Loaded world map";
   public static String bu = "";
   public static String bv = "Connection timed out.";
   public static String bw = "";
   public static String Strings_loadingWordpack = "Loading wordpack - ";
   public static String Strings_loadingSprites = "Loading sprites - ";
   public static String Strings_loadingInterfaces = "Loading interfaces - ";
   public static String ca = "";
   public static String cb = "";
   public static String cc = "Your account has been involved";
   public static String cd = "Press 'change your password' on front page.";
   public static String ce = "No response from server.";
   public static String cf = "Please reload this page.";
   public static String cg = "This world is full.";
   public static String ch = "Bad session id.";
   public static String ci = "Please try using a different world.";
   public static String cj = "Unable to connect.";
   public static String ck = "world you were using has become unavailable.";
   public static String cl = "";
   public static String cm = "RuneScape has been updated!";
   public static String cn = "in serious rule breaking.";
   public static String co = "Login limit exceeded.";
   public static String cp = "We suspect someone knows your password.";
   public static String cq = "Please try again later.";
   public static String cr = "Please use a different world.";
   public static String cs = "";
   public static String ct = "";
   public static String cu = "Either your account is still logged in, or the last";
   public static String cv = "Login server offline.";
   public static String cw = "";
   public static String cx = "Unable to connect.";
   public static String cy = "";
   public static String cz = "Too many connections from your address.";
   public static String da = "Malformed login packet.";
   public static String db = "Your account has been locked due to";
   public static String dc = "Please subscribe, or use a different world.";
   public static String dd = "This world is running a closed Beta.";
   public static String de = "Press the button below to download it now.";
   public static String df = "suspicious activity.";
   public static String dg = "You can use the Jagex Launcher to continue playing.";
   public static String dh = "To access this free world, log into a";
   public static String di = "Could not complete login.";
   public static String dj = "Sorry invited players only.";
   public static String dk = "The server is being updated.";
   public static String dl = "";
   public static String dm = "";
   public static String dn = "Invalid loginserver requested.";
   public static String do = "";
   public static String dp = "members world and move your character";
   public static String dq = "Please recover your account.";
   public static String dr = "Please try using a different world.";
   public static String ds = "";
   public static String dt = "Please wait 1 minute and try again.";
   public static String du = "to a non-members area.";
   public static String dv = "";
   public static String dw = "You need a members account to login to this world.";
   public static String dx = "Please use a different world.";
   public static String dy = "Please try using a different world.";
   public static String dz = "Too many login attempts.";
   public static String ea = "";
   public static String eb = "";
   public static String ec = "Your account must have a displayname set";
   public static String ed = "Service unavailable.";
   public static String ee = "via the website, or the main game.";
   public static String ef = "";
   public static String eg = "";
   public static String eh = "";
   public static String ei = "in order to play the game.  Please set it";
   public static String ej = "Please contact customer support.";
   public static String Strings_pleaseEnterYourPassword = "Please enter your password.";
   public static String el = "This computers address has been blocked";
   public static String em = "";
   public static String en = "as it was used to break our rules.";
   public static String eo = "";
   public static String ep = "Please try again.";
   public static String eq = "No reply from loginserver.";
   public static String er = "";
   public static String es = "Please try using a different world.";
   public static String et = "Please wait 1 minute and try again.";
   public static String eu = "Unexpected loginserver response.";
   public static String ev = "";
   public static String Strings_pleaseEnterYourUsername = "Please enter your username/email address.";
   public static String ex = "";
   public static String ey = "";
   public static String ez = "Error loading your profile.";
   public static String fa;
   public static String fb;
   public static String fc;
   public static String fd;
   public static String fe = "The unpaid balance on your account needs";
   public static String ff;
   public static String fg;
   public static String fh;
   public static String fi;
   public static String fj;
   public static String fk;
   public static String fl;
   public static String fm;
   public static String fn;
   public static String fo;
   public static String fp;
   public static String fq;
   public static String fr;
   public static String fs = "to be resolved before you can play.";
   public static String ft;
   public static String fu;
   public static String fv;
   public static String fw;
   public static String fx;
   public static String fy;
   public static String fz;
   public static String Strings_hasLoggedOut;
   public static String gb;
   public static String Strings_walkHere;
   public static String Strings_chooseOption;
   public static String Strings_hasLoggedIn;
   public static String Strings_level;
   public static String gg;
   public static String Strings_examine;
   public static String Strings_pleaseWait;
   public static String gj;
   public static String Strings_space;
   public static String Strings_yourFriendListIsFull;
   public static String Strings_skill;
   public static String gn;
   public static String go;
   public static String gp;
   public static String Strings_close;
   public static String gr;
   public static String gs;
   public static String Strings_unableToFind;
   public static String Strings_use;
   public static String gv;
   public static String Strings_moreOptions;
   public static String gx;
   public static String Strings_attack;
   public static String Strings_isAlreadyOnYourFriendList;
   public static String ha;
   public static String hb;
   public static String hc;
   public static String Strings_pleaseRemoveFriend;
   public static String he;
   public static String hf;
   public static String hg;
   public static String hh;
   public static String hi;
   public static String hj;
   public static String hk;
   public static String hl;
   public static String hm;
   public static String hn;
   public static String ho;
   public static String hp;
   public static String hq;
   public static String hr;
   public static String hs;
   public static String ht;
   public static String Strings_pleaseRemoveIgnore;
   public static String Strings_fromYourFriendListFirst;
   public static String Strings_yourIgnoreListIsFull;
   public static String Strings_fromYourIgnoreListFirst;
   public static String hy;
   public static String hz;
   public static String ia;
   public static String Strings_theProtectItemPrayerWill;
   public static String ic;
   public static String Strings_playersCanAttackEachOther;
   public static String ie;
   public static String if;
   public static String ig;
   public static String ih;
   public static String ii;
   public static String Strings_thisIsAPvpWorld;
   public static String ik;
   public static String il;
   public static String Strings_warning;
   public static String in;
   public static String io;
   public static String ip;
   public static String iq;
   public static String ir;
   public static String is;
   public static String Strings_almostEverywhere;
   public static String iu;
   public static String iv;
   public static String iw;
   public static String Strings_thisIsAHighRiskWorld;
   public static String iy;
   public static String iz;
   public static String Strings_welcomeToRuneScape;
   public static String Strings_newUser;
   public static String Strings_notWorkOnThisWorld;
   public static String jd;
   public static String je;
   public static String jf;
   public static String Strings_playersCanAttackEachOtherAlmostEverywhere;
   public static String jh;
   public static String Strings_thisIsAHighRiskPvpWorld;
   public static String jj;
   public static String Strings_yourNormalAccountWillNotBeAffected;
   public static String Strings_cancel;
   public static String jm;
   public static String Strings_connectingToServer;
   public static String Strings_thisIsABetaWorld;
   public static String Strings_password;
   public static String jq;
   public static String jr;
   public static String js;
   public static String Strings_pin;
   public static String ju;
   public static String jv;
   public static String jw;
   public static String Strings_andTheProtectItemPrayerWontWork;
   public static String Strings_login;
   public static String Strings_existingUser;
   public static String kc;
   public static String ke;
   public static String kf;
   public static String kh;
   public static String km;
   public static String kn;
   public static String kp;
   public static String ks;
   public static String ku;
   public static String ky;
   public static String kz;
   public static String la;
   public static String lb;
   public static String lc;
   public static String ld;
   public static String le;
   public static String lf;
   public static String lg;
   public static String lh;
   public static String li;
   public static String lj;
   public static String lk;
   public static String ll;
   public static String lm;
   public static String ln;
   public static String lo;
   public static String lp;
   public static String lq;
   public static String lr;
   public static String ls;
   public static String lt;
   public static String lu;
   public static String lv;
   public static String lw;
   public static String lx;
   public static String ly;
   public static String lz;
   public static String ma;
   public static String Strings_loading;
   public static String mc;
   public static String md;
   public static String me;
   public static String mf;
   public static String mg;
   public static String mh;
   public static String mi;
   public static String mj;
   public static String mk;
   public static String ml;
   public static String mm;
   public static String mn;
   public static String mo;
   public static String mp;
   public static String mq;
   public static String mr;
   public static String ms;
   public static String mt;
   public static String mu;
   public static String mv;
   public static String mw;
   public static String mx;
   public static String my;
   public static String mz;
   public static String ns;
   public static String nw;
   public static String nz;
   static String bj = "Please visit the support page for assistance.";

   static {
      fi = bj;
      fh = "Your account is currently inaccessible.";
      fl = "Please try again in a few minutes.";
      fp = "";
      fo = "You need to vote to play!";
      fx = "Visit runescape.com and vote,";
      fd = "and then come back here!";
      fb = "Sorry, but your account is not eligible to play.";
      fn = "For more information, please take a look at";
      fz = "our privacy policy.";
      fa = "Privacy Policy";
      fy = "Enter the 6-digit code generated by your";
      fw = "authenticator app.";
      fr = "";
      fv = "The code you entered was incorrect.";
      fq = "Please try again.";
      fc = "";
      ff = "Login attempt timed out.";
      fj = "Please try again.";
      fg = "";
      fk = "You were signed out.";
      fm = "Please sign in again.";
      ft = "";
      fu = "Failed to login.";
      gr = "Please try again.";
      go = "";
      gs = "Unexpected server response";
      gj = "Please try using a different world.";
      gg = "";
      Strings_hasLoggedIn = " has logged in.";
      Strings_hasLoggedOut = " has logged out.";
      Strings_unableToFind = "Unable to find ";
      Strings_use = "Use";
      Strings_examine = "Examine";
      Strings_attack = "Attack";
      Strings_chooseOption = "Choose Option";
      Strings_moreOptions = " more options";
      Strings_walkHere = "Walk here";
      Strings_level = "level-";
      Strings_skill = "skill-";
      Strings_pleaseWait = "Please wait...";
      Strings_close = "Close";
      Strings_space = " ";
      gb = "M";
      gp = "M";
      gn = "K";
      gv = "K";
      gx = "World";
      Strings_yourFriendListIsFull = "Your friend list is full. Max of 200 for free users, and 400 for members";
      Strings_isAlreadyOnYourFriendList = " is already on your friend list";
      Strings_yourIgnoreListIsFull = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      hi = " is already on your ignore list";
      hj = "You can't add yourself to your own friend list";
      hm = "You can't add yourself to your own ignore list";
      Strings_pleaseRemoveIgnore = "Please remove ";
      Strings_fromYourIgnoreListFirst = " from your ignore list first";
      Strings_pleaseRemoveFriend = "Please remove ";
      Strings_fromYourFriendListFirst = " from your friend list first";
      hs = "yellow:";
      hn = "yellow:";
      hl = "red:";
      hh = "red:";
      hr = "green:";
      hc = "green:";
      hg = "cyan:";
      ho = "cyan:";
      ht = "purple:";
      hb = "purple:";
      hq = "white:";
      hz = "white:";
      hk = "flash1:";
      ha = "flash1:";
      hp = "flash2:";
      he = "flash2:";
      hf = "flash3:";
      hy = "flash3:";
      if = "glow1:";
      ia = "glow1:";
      iu = "glow2:";
      iw = "glow2:";
      iy = "glow3:";
      iz = "glow3:";
      ig = "wave:";
      ih = "wave:";
      il = "wave2:";
      is = "wave2:";
      in = "shake:";
      ic = "shake:";
      ii = "scroll:";
      ik = "scroll:";
      ie = "slide:";
      iq = "slide:";
      iv = "RuneScape is loading - please wait...";
      ir = "";
      io = "Enter your username/email & password.";
      ip = "";
      Strings_warning = "Warning!";
      Strings_thisIsAPvpWorld = "This is a <col=ff0000>PvP<col=ffffff> world.";
      Strings_playersCanAttackEachOther = "Players can attack each other";
      Strings_almostEverywhere = "almost everywhere.";
      Strings_thisIsAHighRiskWorld = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      Strings_theProtectItemPrayerWill = "The Protect Item prayer will";
      Strings_notWorkOnThisWorld = "not work on this world.";
      Strings_thisIsAHighRiskPvpWorld = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      Strings_playersCanAttackEachOtherAlmostEverywhere = "Players can attack each other almost everywhere";
      Strings_andTheProtectItemPrayerWontWork = "and the Protect Item prayer won't work.";
      Strings_thisIsABetaWorld = "This is a <col=00ffff>Beta<col=ffffff> world.";
      Strings_yourNormalAccountWillNotBeAffected = "Your normal account will not be affected.";
      jq = "";
      je = "Authenticator";
      jj = "<u=ff>Can't Log In?</u>";
      jm = "";
      Strings_connectingToServer = "Connecting to server...";
      jd = "";
      jf = "The game servers are currently being updated.";
      jw = "Please wait a few minutes and try again.";
      js = "";
      jr = "";
      jv = "You were disconnected from the server.";
      jh = "";
      Strings_login = "Login: ";
      Strings_password = "Password: ";
      Strings_pin = "PIN: ";
      Strings_welcomeToRuneScape = "Welcome to RuneScape";
      Strings_newUser = "New User";
      Strings_existingUser = "Existing User";
      ju = "Login";
      Strings_cancel = "Cancel";
      kc = "Remember username";
      ku = "Hide username";
      ke = "Incorrect username or password.";
      ky = "If you have upgraded to a Jagex Account, you";
      kh = "need to log in using the <u=ffd200><col=ffd200>Jagex Launcher</col></u> instead.";
      kp = "Try again";
      kf = "Forgotten password?";
      ks = "Forgotten your password?";
      kn = "Username/email: ";
      kz = "Recover";
      km = "Back";
      lv = "Can't login? Click here.";
      lm = "Still having trouble logging in?";
      lg = "Having trouble logging in?";
      ls = "";
      lf = "Page has opened in the browser.";
      li = "";
      lu = "Please enter your username.";
      lk = "If you created your account after November";
      lh = "2010, this will be the creation email address.";
      la = ls;
      lp = lf;
      ly = li;
      ln = "";
      lt = "Error connecting to server.";
      lz = "";
      lc = "The part of the website you are trying";
      ld = "to connect to is offline at the moment.";
      lq = "Please try again later.";
      lj = "Sorry, there was an error trying to";
      ll = "log you in to this part of the website.";
      le = "Please try again later.";
      lb = "";
      lx = "Error connecting to server.";
      lo = "";
      lw = "You must enter a valid login to proceed. For accounts";
      lr = "created after 24th November 2010, please use your";
      mt = "email address. Otherwise please use your username.";
      mw = "Your date of birth isn't set.";
      mz = "Please verify your account status by";
      mu = "setting your date of birth.";
      mq = "Set Date of Birth";
      mm = "Your date of birth information is waiting";
      me = "to be reviewed by our staff.";
      mv = "It will be processed shortly.";
      mx = "Before using this app, please read and accept our";
      ma = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      mp = "<col=ffd200>agreement (EULA)</col>.";
      mj = "By accepting, you agree to these documents.";
      ms = "You must accept our terms of use, privacy policy,";
      mc = "and end user licence agreement to continue.";
      mh = "Accept";
      mg = "Decline";
      mo = "Select a world";
      mn = "Members only world";
      mi = "Free world";
      md = "World";
      mr = "Players";
      ml = "Location";
      mf = "Type";
      my = "OFF";
      mk = "FULL";
      Strings_loading = "Loading...";
      nz = "Click to switch";
      nw = "Download Launcher";
      ns = "https://oldschool.runescape.com/launcher";
   }

   public static final Rasterizer3D af_renamed(byte[] var0) {
      BufferedImage var2 = null;

      try {
         Class var3 = ImageIO.class;
         synchronized(ImageIO.class) {
            var2 = ImageIO.read(new ByteArrayInputStream(var0));
         }

         int var10 = var2.getWidth();
         int var4 = var2.getHeight();
         int[] var5 = new int[var10 * var4];
         PixelGrabber var6 = new PixelGrabber(var2, 0, 0, var10, var4, var5, 0, var10);
         var6.grabPixels();
         return new Rasterizer3D(var5, var10, var4);
      } catch (IOException var8) {
      } catch (InterruptedException var9) {
      }

      return new Rasterizer3D(0, 0);
   }

   public static void at_renamed() {
      MapElementType.MapElementType_cachedSprites.clear();
   }

   static IndexedSprite al_renamed() {
      IndexedSprite var1 = new IndexedSprite();
      var1.width = -822007097 * tx.an;
      var1.height = tx.aw * 378525975;
      var1.xOffset = tx.ac[0];
      var1.yOffset = ar.au[0];
      var1.subWidth = dd.ab[0];
      var1.subHeight = fd.aq[0];
      var1.palette = pc.al;
      var1.pixels = VarBitType.at[0];
      pk.ay_renamed();
      return var1;
   }

   Strings() throws Throwable {
      throw new Error();
   }
}
